### ISSUE TITLE
Task 1 - Criar o desgin that pagina

### ISSUE THREAD

**Issue by Fp-Sena** [Fp-Sena/JogoTempoReacao#3]
Depois que voce ja tiver confirmado que entendeu os requisitos da task: 

O primeiro ponto vai ser criar o design that pagina.

Use o video que eu mandei como referencia, mas nao precisa esta iguazinho voce pode fazer no estilho que achar mais legal.
Se se sentir confortavel com estilos eu faria algo bem legal, com tudo alinhado no centro por exemplo.

O basico do design deve ter:
- O nome do jogo
- Uma parte para mostrar o tempo de reacao do usuario
- e um quadrado preto
- E dentro do quadrado algumas formas diferentes em cores diferentes

Para fazer isso voce pode dar uma olhada nessas referencia:
[div html tutorial](https://www.w3schools.com/html//html_div.asp) (Ingles mas voce pode traduzir)
https://www.freecodecamp.org/portuguese/news/formas-em-css-explicadas-como-desenhar-um-circulo-um-triangulo-e-mais-com-css-puro/

Qualquer duvida pode comentar aqui!

Tenta nao usar nada que gere o codigo para voce, entao nao usa chatGPT ou qualquer coisa assim por que voce vai estar roubando seu aprendizado. Tenha paciencia para fazer devagar e passar pelo processo de escrever pelo menos no comeco ate voce acostumar, depois voce pode gerar as coisas para ir mais rapido. Mas por enquanto quando voce pesquisar ou perguntar algo para o chatGPT nao copia e cola a resposta, digita tudo e se tiver algum coisa que nao entender pesquisa.

Pode me perguntar aqui tambem se estiver travado

**Comment by ls-ramos** [comment]
Boa ficou legal para o comeco!
